<?php


namespace App\Model\Table;


use Cake\ORM\Table;
use App\Model\Behavior\CsvBehavior;

class CsvImportsTable extends Table
{
    public $file;

    public function initialize(array $config): void
    {
        $this->addBehavior('Csv');
        $this->setPrimaryKey('id');
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    public function import($filename, $fields = [], $options = [])
    {
        $results = $this->importCsv("files/$filename", $fields, $options);
        if(is_array($results)){
            $columns = array_keys($results[0]);
            $schema = collection($columns)
                ->reduce(function($accum, $column){
                    $accum[$column] = [
                        'type' => 'char',
                        'length' => 256
                    ];
                    return $accum;
                }, []);
            $this->setSchema($schema);
            $entities = $this->newEntities($results);
        }
        else {
            $entities = [];
        }
//        $keyed = collection($entities)
//            ->reduce(function($accum, $entity){
//                $accum[$entity->stock_number] = $entity;
//                return $accum;
//            }, []);
        return $entities;
    }


}
